title: INU 기술 블로그
baseurl: ""
url: "https://inudevs.github.io/"

social:
  facebook: https://www.facebook.com/2019inu
  github: https://github.com/inudevs

sass:
  sass_dir: _scss
  style: compressed

g-analytics: UA-143594772-1

markdown: kramdown
plugins:
  - jekyll-feed
